"Filed out from Dolphin Smalltalk/Version 2.1"!

Model subclass: #TestingFlowBlockOr
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''!

TestingFlowBlockOr class instanceVariableNames: ''!

TestingFlowBlockOr comment: ''!

!TestingFlowBlockOr categoriesForClass!No category! !

!TestingFlowBlockOr methodsFor!

displayOn: aStream 
	aStream nextPut: $+. 
! !

!TestingFlowBlockOr categoriesFor: #displayOn:!no category! !

