"Filed out from Dolphin Smalltalk/Version 2.1"!

Model subclass: #TestingFlowBlockStart
	instanceVariableNames: 'associatedEnd'
	classVariableNames: ''
	poolDictionaries: ''!

TestingFlowBlockStart class instanceVariableNames: ''!

TestingFlowBlockStart comment: ''!

!TestingFlowBlockStart categoriesForClass!No category! !

!TestingFlowBlockStart methodsFor!

associatedEnd
	^associatedEnd!

associatedEnd: aBlockstart
	associatedEnd := aBlockstart!

displayOn: aStream 
	aStream nextPut: $[. 
! !

!TestingFlowBlockStart categoriesFor: #associatedEnd!no category! !
!TestingFlowBlockStart categoriesFor: #associatedEnd:!no category! !
!TestingFlowBlockStart categoriesFor: #displayOn:!no category! !

